apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgagent
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgagent
  template:
    metadata:
      labels:
        app: pgagent
    spec:
      containers:
      - name: pgagent
        image: local-pgagent-scheduler:v1
        imagePullPolicy: IfNotPresent
        args:
          - "-f"
          - "host=$(PGHOST) dbname=$(PGDATABASE) user=$(PGUSER)"
        env:
          - name: PGHOST
            value: my-database-rw
          - name: PGDATABASE
            value: postgres
          - name: PGUSER
            value: postgres
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: my-database-superuser
                key: password
