apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  source:
    repoURL: https://github.com/BetrajJ/cnpgtest.git
    targetRevision: HEAD
    path: helm-charts/cnpg-operator
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: 
      - CreateNamespace=true
      - ServerSideApply=true
