apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: dev
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Daemon       off
        Log_Level    info
    [INPUT]
        Name         tail
        Path         /var/log/postgresql/*.log
        Tag          postgres.logs
    [OUTPUT]
        Name         opensearch
        Match        postgres.logs
        Host         opensearch-cluster-master.opensearch.svc.cluster.local
        Port         9200
        Index        postgres-logs
        Type         postgres
        Suppress_Type_Name Off
