apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - fluent-bit-config.yaml
  - sealed-backup-creds.yaml
patches:
  - path: patch-dev.yaml
    target:
      kind: Cluster
      name: my-database
configMapGenerator:
  - name: my-database-configmap
    files:
      - postgresschema.sql
    options:
      disableNameSuffixHash: true
