apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - fluent-bit-config.yaml
patches:
  - path: patch-dev.yaml
    target:
      kind: Cluster
      name: my-database
secretGenerator:
  # MinIO credentials
  - name: backup-creds
    literals:
      - ACCESS_KEY_ID=minioadmin
      - SECRET_ACCESS_KEY=minioadmin
  # PostgreSQL connection string
  - name: my-database-connection
    literals:
      - url=postgresql://postgres:postgres@my-database-rw.dev.svc.cluster.local:5432/postgres
    options:
      disableNameSuffixHash: true  
configMapGenerator:
  - name: my-database-configmap
    files:
      - schema.sql
    options:
      disableNameSuffixHash: true      
