apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-database
spec:
  instances: 1
  sidecars:
    - name: fluent-bit-sidecar
      image: fluent/fluent-bit:2.2.2
      volumeMounts:
        - name: fluentbit-config
          mountPath: /fluent-bit/etc
        - name: postgresql-log-volume
          mountPath: /var/log/postgresql
  volumes:
    - name: fluentbit-config
      configMap:
        name: fluent-bit-config
    - name: postgresql-log-volume
      emptyDir: {}
