---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backup-creds
  namespace: dev
spec:
  encryptedData:
    ACCESS_KEY_ID: AgChw0GnXMl98A1F5BFqyQ5rmbii3qdDHoytVwTR2EZbawUhGSdg9KwTqTwldLIx8e8VoNAnkfQ/dcv/vfnNlFljaCnp9C9NLqTcMFfchzGnyV808v7q+PVkEx8TV+lKqfL2RuOV+g1QGyY/mgXdnQ6+eTHUBkpneeG2QRN3mUhTXa+lAZIiSpQT9wF+/wSiColrQEEZW5ft7Ue9BaJLgD8zrpeM/X1aBhEfMTcfaAXDMYg2khUYQAOFmhEI9FUI95tApXBbQOLC1RCl9qpMR0aeCByZX5RzaUTUHp0li0azGYzVr+sCATUoBhI8u7/6QvDcLWpDW5thr7U70BfA+rt/fAzOKqi8jrTIYZtmMfSZOO4GVm9ZZNWaciNyptbFuxyz3JXa33m9al1VbNpWAUfR0OSxzw1ybxSLVaTIAhtiRbO5fHsJ6caHxS3cKNNLLuybGkuEmfTc/W+hI0tzYgKYF7VrrWGHQWULSEZdY8AdzOO/H1f3Au9bVWgyqK7/DnpSFq5P079hywG4fjut4ZJXR9ktzM7PWi8X+F4aGQU6LSnMKKSMfBdbxMbfTNcqbpuODMBtZnC5oybLMk6d3EWpc7N/l0u2Fef54HsEyOAT2KZGJo8MkUjgEgmfI1PS8ueA/mjjkiFgb3+ibe3E9kVKySWyGzGLAOXsMR4WfQfEcLDONnpQlkNacGdt02GoWtNm7z7TmjLQKsOdMdRADRYxD8Ihjw==
    ACCESS_SECRET_KEY: AgBOy2YWCkDGFqErCSGGecERfFaR6Z5xuVou0OhHTVWZYR5ML8jbnWrSQe3c/B+yrmDY2xAeidLV2dTj3OEPaLRO6yu+DPSxvmAPMm8jjzMOssO8UjLHPrF+NvS3RsbxjqYNLPkt0heUnje0qZ/LgCXVZXAL53Gc5hWqSxaCKFtBVDB1vF3lLC0WUTMUMLhNbnXXD6yE4HPWkgnBm5zFwKOxBP/5kyIpqp/yrLquvTojka3TokDkkdif6cTvb8XocvQJXfEGAimrwvHFVhbs5UuOQW98C4jtrFX0uTLy1w5x6fQDRa6O2u43VcSMyZc0Z6pK8rxTemY7ko5KOPfrZmZIB7ImO//5zZeGu0F4bUdCuFlrNonDDy0KOTGS4YL5y7W8ooVJSlKSqFuHKJWsGzKmvN7aL41ykO/VthXxNSurvH9LwgdlgGWDGI/jenrh1O/5Ov73pvgPSQCLOhrygzEkbwQzkpWeXXEa9dRbPH+cI8YggVeoqFSjI69CKxcoV0wVOfP3EFjPd3uh46mO2RU48VS07ulJxrNtXT2EZ4aOFtfwUSvW3d2NGEiT19m716oWRcWWUGKXsnduK4kpPvf2WWYNffK5XRNJI4LQl3UGpyEohddHn2orP8e8jm1RmLxte2k/NC9sr43frEMIQbTPlU/OOvcDaLVSS6VPeYBSVPWL+Wqe/1Qni7AXlYWsBdmCeIjBR2StZyuh+nYXcgwGhg47v6O2aFGbnGP7sKeC0vAC0xzZoWc6
  template:
    metadata:
      name: backup-creds
      namespace: dev
