apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: my-database-schema
spec:
  # Reference a Secret for the connection URL
  url:
    secretKeyRef:
      name: my-database-connection
      key: url

  # Use SSL for a secure connection
  sql:
    - "ALTER ROLE postgres SET sslmode = verify-full;"

  # Reference the schema from a ConfigMap
  schema:
    configMapKeyRef:
      name: my-database-configmap
      key: schema.sql
