apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: my-database-schema
spec:
  credentials:
    scheme: postgres
    host: my-database-rw.dev.svc.cluster.local
    user: app
    passwordFrom:
      secretKeyRef:
        name: my-database-app
        key: password
    database: app
    port: 5432
    parameters:
      sslmode: disable

  schema:
    configMapKeyRef:
      name: my-database-configmap
      key: schema.sql    
