apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: my-database-schema
spec:
  urlFrom:
    secretKeyRef:
      name: my-database-connection
      key: url

  # Reference the schema from a ConfigMap
  schema:
    configMapKeyRef:
      name: my-database-configmap
      key: schema.sql
