apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - atlas-schema.yaml
  - cert-manager-issuer.yaml
  - postgres-cluster.yaml
  - on-demand-backup.yaml
  - scheduled-backup.yaml
