# kustomize/base/on-demand-backup.yaml
# This manifest creates a one-time, on-demand backup of your database.

apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: my-database-manual-backup-20250825
spec:
  # The name of the cluster you want to back up
  cluster:
    name: my-database
