apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-database
spec:
  enableSuperuserAccess: true
  instances: 3
  replicationSlots:
    highAvailability:
      enabled: true

  # PostgreSQL configuration
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
      logging_collector: 'on'
      max_wal_senders: "10"
      max_replication_slots: "10"
      wal_level: "logical"

  # Storage configuration
  storage:
    size: 12Gi
    storageClass: hostpath

  # Backup configuration
  backup:
    barmanObjectStore:
      destinationPath: "s3://ssecaturldev/cnpg-database-backup/"
      s3Credentials:
        # Use a Secret for access keys, no hardcoding
        accessKeyId:
          name: backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backup-creds
          key: ACCESS_SECRET_KEY
    retentionPolicy: "1d"

  # Monitoring configuration
  monitoring:
    enablePodMonitor: true
  # Antiaffinity  
  affinity:
    podAntiAffinityType: preferred
    topologyKey: kubernetes.io/hostnames
