# kustomize/base/scheduled-backup.yaml
# This manifest creates a scheduled backup that will run periodically.

apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: my-database-scheduled-backup1
spec:
  # The name of the cluster you want to back up
  cluster:
    name: my-database

  # This is the schedule using standard cron syntax.
  schedule: "0 0 * * *"
  immediate: true
