# kustomize/base/scheduled-backup.yaml
# This manifest creates a scheduled backup that will run periodically.

apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: my-database-scheduled-backup
spec:
  # The name of the cluster you want to back up
  cluster:
    name: my-database

  barmanObjectStore:
    destinationPath: "s3://cnpg-backups-my-database"
    endpointURL: "http://minio-service.minio-system.svc.cluster.local:9000"
    s3Credentials:
      accessKeyId:
        name: backup-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: backup-creds
        key: SECRET_ACCESS_KEY

  # This is the schedule using standard cron syntax.
  schedule: "0 0 * * *"
  immediate: true
